// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABtu8vKBSQEU8N6FBEh5IpRYNZdSRKIb4',
    appId: '1:419165124800:web:8c8a7e9890424e0cbe9525',
    messagingSenderId: '419165124800',
    projectId: 'chat-app-ff868',
    authDomain: 'chat-app-ff868.firebaseapp.com',
    storageBucket: 'chat-app-ff868.firebasestorage.app',
    measurementId: 'G-XB5JNRX5F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv6oFI3RhTo3r9e9Fr7YCHR4GK7urZouU',
    appId: '1:419165124800:android:133f9781e744ebf4be9525',
    messagingSenderId: '419165124800',
    projectId: 'chat-app-ff868',
    storageBucket: 'chat-app-ff868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnh-krNZkQWgTf-0dPYyl-njPxukGzwAw',
    appId: '1:419165124800:ios:f1119194cbe8398fbe9525',
    messagingSenderId: '419165124800',
    projectId: 'chat-app-ff868',
    storageBucket: 'chat-app-ff868.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnh-krNZkQWgTf-0dPYyl-njPxukGzwAw',
    appId: '1:419165124800:ios:f1119194cbe8398fbe9525',
    messagingSenderId: '419165124800',
    projectId: 'chat-app-ff868',
    storageBucket: 'chat-app-ff868.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
